openapi: 3.0.0
info:
  title: Sami API
  version: 0.1.0
servers:
  - url: https://api.sample.com/v1
paths:
  /users:
    get:
      summary: Get users
      responses:
        '200':
          description: JSON array of users
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
  /users/{id}:
    get:
      summary: Get user by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: User object
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  name:
                    type: string
        '404':
          description: User not found
